### ISSUE TITLE
As a Admin/Employee I would like to Login to the Application.

### ISSUE THREAD

**Issue by sumitknoldus** [sumitknoldus/yourManager#12]
**Acceptance Criteria**
1) Login page exists with Knoldus logo in it.
2) Validation exists.
3) Re-Route to Dashboard once logged in.
4) Logout functionality should exist.

**Comment by sumitknoldus** [comment]
**Sub-Tasks**

- [ ] Create Template for Signin. 
- [ ] Create Component/Controller for Signin.
- [ ] Create Service/Factory for Signin.
- [ ] Bind the View, Component and Service for Signin functionality.
- [ ] Create the route file and Implement the Route for Signin.
- [ ] Create Signin Controller Methods in User Controller.
- [ ] Create User Controller and its api for Signin. 
- [ ] Create all the required queries in UserModel for Signin.
